---
language: node_js
node_js:
  - "6"
  - "7"

sudo: false
cache: yarn

before_script:
  - yarn upgrade joda-project/joda-core
  - yarn upgrade joda-project/joda-i18n
  - yarn add joda-project/joda-misc --dev

script:
  - yarn test
